#pragma once

#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416

#define MAP_WIDTH 16
#define MAP_HEIGHT 13

#define MARIO_GRAVITY_A 1600.0f
#define MARIO_WALK_A 160.0f
#define MARIO_RUN_A 340.0f
#define MARIO_GROUND_FRICTION_A 600.0f
#define MARIO_GROUND_CAP 140.0f
#define MARIO_START_VELOCITY_WALK 24.0f
#define MARIO_GROUND_CAP_RUN 240.0f
#define MARIO_START_VELOCITY_RUN 40.0f
#define MARIO_JUMP_SPEED 350.0f
#define MARIO_JUMP_TIME 0.18f
#define MARIO_BOUNCE_SPEED 100.0f
#define MARIO_WALK_TIME 0.15f
#define MARIO_RUN_TIME 0.08f

#define INJURED_TIME_GREEN 2.5f
#define INJURED_TIME_RED 2.25f
#define INJURED_TIME_PURPLE 2.0f
#define KOOPA_GREEN_SPEED 96.0f
#define KOOPA_RED_SPEED 128.0f
#define KOOPA_PURPLE_SPEED 160.0f
#define KOOPA_WALK_TIME 0.15f
#define KOOPA_DIE_TIME 0.5f

#define KOOPA_SPAWN_TIME 5.0f
#define COIN_SPAWN_TIME 12.0f
#define COIN_RADIUS 11.0f

#define COIN_ANIMATION_TIME 0.1f
#define COIN_MOVE_SPEED 100.0f

#define MARIO_WIDTH 32
#define MARIO_HEIGHT 32

#define TILE_WIDTH 32

#define SCREENSHAKE_DURATION 0.25f