#pragma once

#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416

#define MAP_WIDTH 16
#define MAP_HEIGHT 13

#define MARIO_GRAVITY_A 1.1f
#define MARIO_WALK_A 0.15f
#define MARIO_RUN_A 0.3f
#define MARIO_GROUND_FRICTION_A 0.4f
#define MARIO_GROUND_CAP 120.0f
#define MARIO_START_VELOCITY_WALK 15.0f
#define MARIO_GROUND_CAP_RUN 220.0f
#define MARIO_START_VELOCITY_RUN 22.0f
#define MARIO_JUMP_SPEED 320.0f
#define MARIO_JUMP_TIME 0.14f

#define INJURED_TIME 2.5f
#define KOOPA_HIT_JUMP_V 100.0f
#define KOOPA_SPEED 96.0f

#define MARIO_WIDTH 32
#define MARIO_HEIGHT 32

#define TILE_WIDTH 32

#define SCREENSHAKE_DURATION 0.25f