#pragma once

#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416

#define MAP_WIDTH 16
#define MAP_HEIGHT 13

#define MARIO_GRAVITY_A 0.9f
#define MARIO_WALK_A 0.1f
#define MARIO_RUN_A 0.22f
#define MARIO_GROUND_FRICTION_A 0.2f
#define MARIO_GROUND_CAP 120.0f
#define MARIO_START_VELOCITY_WALK 12.0f
#define MARIO_GROUND_CAP_RUN 220.0f
#define MARIO_START_VELOCITY_RUN 20.0f
#define MARIO_JUMP_SPEED 350.0f
#define MARIO_JUMP_TIME 0.12f

#define MARIO_WIDTH 32
#define MARIO_HEIGHT 32

#define TILE_WIDTH 32